-- ============================================================
-- Programming Practice Progress Management System
-- Oracle SQL Schema (Strictly Normalized, 3NF)
-- ============================================================

-- Disable FK constraints during creation
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- ============================================================
-- 1. ROLE & USER TABLES
-- ============================================================

CREATE TABLE Role (
    RoleID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoleName VARCHAR2(50) NOT NULL UNIQUE   -- 'admin' | 'user'
);

CREATE TABLE "User" (
    UserID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FullName     VARCHAR2(255) NOT NULL,
    Email        VARCHAR2(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR2(255) NOT NULL,
    CF_Handle    VARCHAR2(100),
    IsVerified   NUMBER(1) DEFAULT 0 NOT NULL CHECK (IsVerified IN (0, 1))
);

CREATE TABLE UserRole (
    UserRoleID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID     NUMBER NOT NULL,
    RoleID     NUMBER NOT NULL,
    CONSTRAINT fk_userrole_user FOREIGN KEY (UserID) REFERENCES "User"(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_userrole_role FOREIGN KEY (RoleID) REFERENCES Role(RoleID) ON DELETE CASCADE,
    CONSTRAINT uq_user_role UNIQUE (UserID, RoleID)
);

-- ============================================================
-- 2. VERDICT LOOKUP TABLE
-- ============================================================

CREATE TABLE VerdictLookup (
    VerdictID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name        VARCHAR2(10) NOT NULL UNIQUE  -- AC, WA, TLE, MLE, CE
);

-- ============================================================
-- 3. QUESTION & REFERENCE SOLUTION
-- ============================================================

CREATE TABLE Question (
    QuestionID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AdminID    NUMBER NOT NULL,
    CF_Link    VARCHAR2(500) NOT NULL UNIQUE,
    Title      VARCHAR2(500),
    Rating     NUMBER(4) CHECK (Rating BETWEEN 800 AND 3500),
    Tags       VARCHAR2(1000),
    Hint       CLOB,
    IsVerified NUMBER(1) DEFAULT 1 CHECK (IsVerified IN (0, 1)),
    CreatedAt  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_question_admin FOREIGN KEY (AdminID) REFERENCES "User"(UserID)
);

CREATE TABLE ReferenceSolution (
    RefSolID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    QuestionID  NUMBER NOT NULL,
    Description VARCHAR2(2000),
    CodeSnippet CLOB,
    Language    VARCHAR2(50),
    CONSTRAINT fk_refsol_question FOREIGN KEY (QuestionID) REFERENCES Question(QuestionID) ON DELETE CASCADE
);

-- ============================================================
-- 4. SUBMISSION
-- ============================================================

CREATE TABLE Submission (
    SubmissionID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID        NUMBER NOT NULL,
    QuestionID    NUMBER NOT NULL,
    VerdictID     NUMBER NOT NULL,
    SubmittedCode CLOB,
    SubmittedAt   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_sub_user     FOREIGN KEY (UserID)     REFERENCES "User"(UserID)          ON DELETE CASCADE,
    CONSTRAINT fk_sub_question FOREIGN KEY (QuestionID) REFERENCES Question(QuestionID)    ON DELETE CASCADE,
    CONSTRAINT fk_sub_verdict  FOREIGN KEY (VerdictID)  REFERENCES VerdictLookup(VerdictID)
);

-- ============================================================
-- 5. PERSONAL NOTE
-- ============================================================

CREATE TABLE PersonalNote (
    NoteID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID     NUMBER NOT NULL,
    QuestionID NUMBER NOT NULL,
    Content    CLOB,
    UpdatedAt  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_note_user     FOREIGN KEY (UserID)     REFERENCES "User"(UserID)       ON DELETE CASCADE,
    CONSTRAINT fk_note_question FOREIGN KEY (QuestionID) REFERENCES Question(QuestionID) ON DELETE CASCADE,
    CONSTRAINT uq_note UNIQUE (UserID, QuestionID)
);

-- ============================================================
-- 6. USER STATS
-- ============================================================

CREATE TABLE UserStats (
    StatID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID       NUMBER NOT NULL UNIQUE,
    TotalSolved  NUMBER DEFAULT 0 NOT NULL,
    CurrentRank  NUMBER,
    UpdatedAt    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_stats_user FOREIGN KEY (UserID) REFERENCES "User"(UserID) ON DELETE CASCADE
);

-- ============================================================
-- 7. BOOKMARK (User bookmarking questions)
-- ============================================================

CREATE TABLE Bookmark (
    BookmarkID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID     NUMBER NOT NULL,
    QuestionID NUMBER NOT NULL,
    CreatedAt  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_bm_user     FOREIGN KEY (UserID)     REFERENCES "User"(UserID)       ON DELETE CASCADE,
    CONSTRAINT fk_bm_question FOREIGN KEY (QuestionID) REFERENCES Question(QuestionID) ON DELETE CASCADE,
    CONSTRAINT uq_bookmark UNIQUE (UserID, QuestionID)
);

-- ============================================================
-- 8. DISCUSSION & VOTE
-- ============================================================

CREATE TABLE Discussion (
    DiscussionID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    QuestionID   NUMBER NOT NULL,
    UserID       NUMBER NOT NULL,
    ParentID     NUMBER,
    Text         CLOB NOT NULL,
    CreatedAt    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_disc_question FOREIGN KEY (QuestionID) REFERENCES Question(QuestionID) ON DELETE CASCADE,
    CONSTRAINT fk_disc_user     FOREIGN KEY (UserID)     REFERENCES "User"(UserID)       ON DELETE CASCADE,
    CONSTRAINT fk_disc_parent   FOREIGN KEY (ParentID)   REFERENCES Discussion(DiscussionID) ON DELETE CASCADE
);

CREATE TABLE Vote (
    VoteID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID       NUMBER NOT NULL,
    DiscussionID NUMBER NOT NULL,
    Value        NUMBER(1) NOT NULL CHECK (Value IN (1, -1)),
    CONSTRAINT fk_vote_user FOREIGN KEY (UserID)       REFERENCES "User"(UserID)         ON DELETE CASCADE,
    CONSTRAINT fk_vote_disc FOREIGN KEY (DiscussionID) REFERENCES Discussion(DiscussionID) ON DELETE CASCADE,
    CONSTRAINT uq_vote UNIQUE (UserID, DiscussionID)
);

-- ============================================================
-- 9. CF VERIFICATION TOKENS
-- ============================================================

CREATE TABLE CFVerificationToken (
    TokenID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID    NUMBER NOT NULL UNIQUE,
    Token     VARCHAR2(100) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_cftoken_user FOREIGN KEY (UserID) REFERENCES "User"(UserID) ON DELETE CASCADE
);

-- ============================================================
-- 10. SEED DATA
-- ============================================================

INSERT INTO Role (RoleName) VALUES ('admin');
INSERT INTO Role (RoleName) VALUES ('user');

INSERT INTO VerdictLookup (Name) VALUES ('AC');
INSERT INTO VerdictLookup (Name) VALUES ('WA');
INSERT INTO VerdictLookup (Name) VALUES ('TLE');
INSERT INTO VerdictLookup (Name) VALUES ('MLE');
INSERT INTO VerdictLookup (Name) VALUES ('CE');

COMMIT;

-- ============================================================
-- 11. TRIGGERS: Auto-update UserStats on AC submission
-- ============================================================

CREATE OR REPLACE TRIGGER trg_update_stats
AFTER INSERT ON Submission
FOR EACH ROW
DECLARE
    v_verdict_name VerdictLookup.Name%TYPE;
BEGIN
    SELECT Name INTO v_verdict_name
    FROM VerdictLookup
    WHERE VerdictID = :NEW.VerdictID;

    IF v_verdict_name = 'AC' THEN
        MERGE INTO UserStats us
        USING DUAL
        ON (us.UserID = :NEW.UserID)
        WHEN MATCHED THEN
            UPDATE SET
                TotalSolved = TotalSolved + 1,
                UpdatedAt   = SYSTIMESTAMP
        WHEN NOT MATCHED THEN
            INSERT (UserID, TotalSolved, CurrentRank, UpdatedAt)
            VALUES (:NEW.UserID, 1, NULL, SYSTIMESTAMP);
    END IF;
END;
/

-- Recompute global ranks procedure
CREATE OR REPLACE PROCEDURE sp_recompute_ranks AS
BEGIN
    UPDATE UserStats us
    SET CurrentRank = (
        SELECT RANK() OVER (ORDER BY TotalSolved DESC)
        FROM UserStats us2
        WHERE us2.StatID = us.StatID
    );
    COMMIT;
END;
/
